// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfaoiiwdnnklyvectaud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmYW9paXdkbm5rbHl2ZWN0YXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTcyMzYsImV4cCI6MjA2NTY3MzIzNn0.kY6QoiS5YXkLHdrbRPxMZDsg9JS738ELcXvVy4sFXRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);